# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: linux

on:
  push:
  pull_request:
  release:
    types: [ published, created ]

jobs:
  build:
    runs-on: ubuntu-latest

    # Run steps on a matrix of 3 arch/distro combinations
    strategy:
      matrix:
        include:
          - arch: aarch64
            distro: ubuntu18.04

#    strategy:
#      fail-fast: false
#      matrix:
#        include:
#          - { os: ubuntu-latest,   target: linux,   platform: linux-x64    }
#          - { os: ubuntu-latest,   target: linux,   platform: linux-arm64  }
          # - { os: macos-11,       target: darwin,  platform: darwin-x64   }
          # - { os: macos-11,       target: darwin,  platform: darwin-arm64 }
          # - { os: windows-latest, target: windows, platform: win32-ia32   }
          # - { os: windows-latest, target: windows, platform: win32-x64    }
#    runs-on: ${{ matrix.os }}

    steps:
      - name: Publish Test
        if: (github.event_name == 'release')
        run: |
          echo "This would be where the publishing happens"

      - uses: actions/checkout@v2
      - uses: uraimo/run-on-arch-action@v2
        with:
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}

          install: |
            echo "event name: ${{ github.event_name }}"
            apt update
            apt install -y git curl python3
            apt install -y pkg-config libudev-dev libusb-1.0-0-dev
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm install v16
            nvm use v16

          run: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            git clone https://github.com/node-hid/node-hid
            cd node-hid
            npm run prepublishOnly
            npm install --build-from-source
            npm test

      - name: Test
        run: |
          cd node-hid
          ls -alrth build/Release/
          file build/Release/*node


#      - name: install aarch64-linux-gnu
#        if: ${{ matrix.platform == 'linux-arm64' }}
#        run: |
#          sudo apt-get update
#          sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu

      # - name: setup prerequisites (linux)
      #   run: |
      #     uname -a
      #     sudo apt update
      #     sudo apt install pkg-config libudev-dev libusb-1.0-0-dev

      # - name: Use Node.js ${{ matrix.node-version }}
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: ${{ matrix.node-version }}

      # - name: Build node-hid
      #   run: |
      #     git clone https://github.com/node-hid/node-hid
      #     cd node-hid
      #     npm run prepublishOnly
      #     npm install --build-from-source

      # - name: Test
      #   run: |
      #     cd node-hid
      #     npm test
      #     ls -alrth build/Release/
      #     file build/Release/*node


# tests again
