# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: ubuntu-latest,   target: linux,   platform: linux-x64    }
          - { os: ubuntu-latest,   target: linux,   platform: linux-arm64  }
          # - { os: macos-11,       target: darwin,  platform: darwin-x64   }
          # - { os: macos-11,       target: darwin,  platform: darwin-arm64 }
          # - { os: windows-latest, target: windows, platform: win32-ia32   }
          # - { os: windows-latest, target: windows, platform: win32-x64    }

    runs-on: ${{ matrix.os }}
#    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: setup prerequisites (linux)
        run: |
          sudo apt update
          sudo apt install pkg-config libudev-dev libusb-1.0-0-dev

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build node-hid
        run: |
          git clone https://github.com/node-hid/node-hid
          cd node-hid
          npm run prepublishOnly
          npm install --build-from-source

      - name: Test
        run: cd node-hid && npm test

# tests again
